name: Set up Node.js workflow

inputs:
  node-version:
    description: "Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0."

  registry-url:
    description: "Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN."

outputs:
  package-manager:
    description: "The package manager used in the project."
    value: ${{ steps.detect-package-manager.outputs.name }}

runs:
  using: composite

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Detect package manager
      id: detect-package-manager
      shell: bash
      run: |
        if [ -f "${{ github.workspace }}/yarn.lock" ]; then
          echo "name=yarn" >> $GITHUB_OUTPUT
          echo "install-command=install --frozen-lockfile" >> $GITHUB_OUTPUT
          exit 0
        elif [ -f "${{ github.workspace }}/package.json" ]; then
          echo "name=npm" >> $GITHUB_OUTPUT
          echo "install-command=ci" >> $GITHUB_OUTPUT
          exit 0
        else
          echo "Unable to determine package manager as npm or yarn. Make sure there is a package.json or a yarn.lock file in the root directory."
          exit 1
        fi

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ steps.detect-package-manager.outputs.name }}
        registry-url: ${{ inputs.registry-url }}

    - name: Install dependencies
      shell: bash
      run: ${{ steps.detect-package-manager.outputs.name }} ${{ steps.detect-package-manager.outputs.install-command }}
